Fix paths for MDS api changes
opensearch-project/opensearch-dashboards-functional-test pull request #1266
Opened 2024-05-03 14:42 UTC by derek-ho

### Description

[Describe what this change achieves]

### Issues Resolved

[List any issues this PR will resolve]

### Check List

- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-05-03 14:43 UTC, derek-ho commented
<img width="498" alt="Screenshot 2024-05-03 at 10 41 11 AM" src="https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/26328171/85d94046-856d-498b-81b4-75089df4b2c6">
<img width="499" alt="Screenshot 2024-05-03 at 10 40 19 AM" src="https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/26328171/d2042ebe-e3ff-4819-83e4-5d6c2109143b">
<img width="498" alt="Screenshot 2024-05-03 at 10 39 18 AM" src="https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/26328171/e9d688ea-52a0-4106-8170-110084f416fd">
<img width="499" alt="Screenshot 2024-05-03 at 10 38 17 AM" src="https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/26328171/73f981ec-9eb9-4714-ab13-74f3918333ef">
<img width="498" alt="Screenshot 2024-05-03 at 10 37 16 AM" src="https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/26328171/14508bd0-6b25-4b37-b299-e9a901cbacd7">
<img width="497" alt="Screenshot 2024-05-03 at 10 36 00 AM" src="https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/26328171/7260dda0-cbe5-4e07-831e-8c64a8e51876">
<img width="501" alt="Screenshot 2024-05-03 at 10 29 31 AM" src="https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/26328171/69fb8188-cffa-40a7-b28d-fff8f64edcfa">

2024-05-03 15:25 UTC, derek-ho commented
This should also be backported to 2.x and main

2024-05-03 15:33 UTC, cwperks requested changes
The paths need to remain as they are. They define a path to an API. 

Is there another way to handle this?

2024-05-03 18:18 UTC, cwperks approved these changes
Thanks @derek-ho!

2024-05-03 22:32 UTC, merged

2024-05-04 00:20 UTC, SuZhou-Joe commented
@derek-ho Would you mind backport main manually?

2024-05-06 18:16 UTC, derek-ho commented
@SuZhou-Joe raised up manual backport to main here: https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1271