Removing form field in gantt-chart, observability and workbench
opensearch-project/opensearch-dashboards-functional-test pull request #424
Opened 2022-12-13 21:45 UTC by ps48

Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>

### Description

The functional tests for gantt-chart, observability and workbench were over-riding the default cypress form field in api requests to OpenSearch. This was leading to error as form field override is only necessary when this header is set to `x-www-form-urlencoded` 

Solution: Removed the form field as it is not required in the tests.

### Issues Resolved

#313 
#310  
#311  
#312  

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-12-13 21:48 UTC, ps48 commented
Cypress Test run results for the modified tests:

without-security
```
=====================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        9.5.4                                                                          │
  │ Browser:        Electron 94 (headless)                                                         │
  │ Node Version:   v14.20.0 (/Users/sgguruda/.nvm/versions/node/v14.20.0/bin/node)                │
  │ Specs:          1 found (plugins/gantt-chart-dashboards/gantt_ui.spec.js)                      │
  │ Searched:       cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  plugins/gantt-chart-dashboards/gantt_ui.spec.js                                 (1 of 1)


  Dump test data
    ✓ Indexes test data for gantt chart

  Save a gantt chart
    ✓ Creates and saves a gantt chart (9620ms)

  Render and configure a gantt chart
    ✓ Renders no data message
    ✓ Renders the chart (5910ms)

  Configure panel settings
    ✓ Changes y-axis label
    ✓ Changes x-axis label (5870ms)
    ✓ Changes time formats (7563ms)
    ✓ Hides legends

  Add gantt chart to dashboard
    ✓ Adds gantt chart to dashboard


  9 passing (47s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        9                                                                                │
  │ Passing:      9                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     47 seconds                                                                       │
  │ Spec Ran:     plugins/gantt-chart-dashboards/gantt_ui.spec.js                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /Users/sgguruda/work/git_codebase/opensearch-dashboards-fun    (4 seconds)
                          ctional-test/cypress/videos/plugins/gantt-chart-dashboards/               
                          gantt_ui.spec.js.mp4                                                      


=====================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  plugins/gantt-chart-dashboards/gant      00:47        9        9        -        -        - │
  │    t_ui.spec.js                                                                                │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:47        9        9        -        -        -  


=====================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        9.5.4                                                                          │
  │ Browser:        Electron 94 (headless)                                                         │
  │ Node Version:   v14.20.0 (/Users/sgguruda/.nvm/versions/node/v14.20.0/bin/node)                │
  │ Specs:          1 found (plugins/observability-dashboards/0_before.spec.js)                    │
  │ Searched:       cypress/integration/plugins/observability-dashboards/0_before.spec.js          │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  plugins/observability-dashboards/0_before.spec.js                               (1 of 1)


  Before
    ✓ setup completed (13442ms)


  1 passing (14s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     13 seconds                                                                       │
  │ Spec Ran:     plugins/observability-dashboards/0_before.spec.js                                │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /Users/sgguruda/work/git_codebase/opensearch-dashboards-fun     (1 second)
                          ctional-test/cypress/videos/plugins/observability-dashboard               
                          s/0_before.spec.js.mp4                                                    


=====================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  plugins/observability-dashboards/0_      00:13        1        1        -        -        - │
  │    before.spec.js                                                                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:13        1        1        -        -        -  


=====================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        9.5.4                                                                          │
  │ Browser:        Electron 94 (headless)                                                         │
  │ Node Version:   v14.20.0 (/Users/sgguruda/.nvm/versions/node/v14.20.0/bin/node)                │
  │ Specs:          1 found (plugins/query-workbench-dashboards/ui.spec.js)                        │
  │ Searched:       cypress/integration/ [...]

2022-12-13 23:16 UTC, ps48 commented
https://user-images.githubusercontent.com/4348487/207465611-18fa6952-1a9b-45ce-a654-3e24f3fb8041.mp4

https://user-images.githubusercontent.com/4348487/207465624-e673569e-0144-435d-9720-4fd19de85557.mp4

https://user-images.githubusercontent.com/4348487/207465635-76d1f09e-d407-419d-bd66-d93f81184eb2.mp4

2022-12-14 00:22 UTC, CCongWang approved these changes

2022-12-15 19:08 UTC, CCongWang commented
@tianleh do you know why the three plugins pass locally but fail in workflow??

2022-12-15 23:30 UTC, joshuali925 approved these changes
thanks. seems still failing in github actions?

2022-12-16 17:39 UTC, tianleh commented
> @tianleh do you know why the three plugins pass locally but fail in workflow??

@ps48 Could you share more details about your local setup? e.g operating system, browser and test command. From the output you attached, it looks like you are using browser `Electron 94 (headless)` instead of `Chromium 108 (headless) ` used in the Github workflow.

Also could you rerun the workflow a few more times to see if this is an transient issue or a deterministic issue?

2022-12-16 17:56 UTC, tianleh commented
The workflow test artifacts can be checked here https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/3697326419

You can follow these steps to get it: open workflow from the PR page, then click the `Summary` button. @ps48

2022-12-19 23:53 UTC, tianleh requested changes
Please check the workflow failure

2022-12-20 17:29 UTC, ps48 commented
> Please check the workflow failure

@tianleh, as dicussed offline. I'm still waiting for a stable dashboards distribution build in version 3.0.0 which has gantt-charts and Observability plugin built-in.

2023-01-20 18:42 UTC, CCongWang commented
This PR is blocked by failed workflow because we don't have a stable dashboards distribution build in version 3.0.0. I think we can merge the PR for now, since @ps48 has uploaded all local test results.
This PR should be backported to 1.3 - 2.4 for now, and once the current 2.5 release tests are complete, I will backport it to 2.5.
Any comments/concerns/questions?
cc: @tianleh @joshuali925

2023-01-20 18:51 UTC, tianleh commented
> This PR is blocked by failed workflow because we don't have a stable dashboards distribution build in version 3.0.0. I think we can merge the PR for now, since @ps48 has uploaded all local test results.
> This PR should be backported to 1.3 - 2.4 for now, and once the current 2.5 release tests are complete, I will backport it to 2.5.
> Any comments/concerns/questions?
> cc: @tianleh @joshuali925

Looks good to me.

2023-01-24 22:41 UTC, ohltyler approved these changes

2023-01-24 23:47 UTC, merged