Upgrade to cypress 12
opensearch-project/opensearch-dashboards-functional-test pull request #668
Opened 2023-05-24 13:22 UTC by cwperks

### Description

Creating Draft PR to understand what is required to migrate to Cypress 12 from Cypress 9.

- Cypress 10 release blog: https://www.cypress.io/blog/2022/06/01/cypress-10-release/
- Cypress 11 release blog: https://www.cypress.io/blog/2022/11/08/announcing-cypress-11/
- Cypress 12 CHANGELOG: https://docs.cypress.io/guides/references/changelog#12-0-0

For this PR to get the specs working I had to:

- Rename `cypress/support/index.js` -> `cypress/support/e2e.js`
- Turn off rule `"cypress/unsafe-to-chain-command": "off"` as there were 290 violations - I will file a follow-up issue to resolve the violations and re-enable the rule.
- Added `specPattern` to the `e2e` section of the cypress config
- The `e2e` section of the cypress config was added by another user with a similar [PR](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/598), I copied that into here and the only modification I made was adding the `specPattern` into that section. 

### Issues Resolved

https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/408

### Check List

- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-05-24 17:08 UTC, peterzhuamazon commented
Possible replacement of this one PR: 
* https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/598

2023-05-24 18:04 UTC, peterzhuamazon requested changes

2023-05-24 18:04 UTC, peterzhuamazon commented on package.json
> +    "cypress": "^12.13.0",
This needs to be fixed to `12.13.0` instead of `^12.13.0`, as our image will only carry one version and will not install newer versions on the fly.

2023-05-24 18:04 UTC, peterzhuamazon commented on package.json
> +    "cypress": "^12.13.0",
This is also specific for the arm64 version to be compiled from source.

2023-05-24 19:11 UTC, peterzhuamazon commented on package.json
> +    "cypress": "^12.13.0",
Thanks.

2023-05-24 19:11 UTC, peterzhuamazon commented
Waiting:
* https://github.com/opensearch-project/opensearch-build/pull/3552

2023-05-24 22:13 UTC, peterzhuamazon approved these changes

2023-05-25 03:45 UTC, peterzhuamazon commented
The snapshot workflow has 1 error on cypress9 but 12 errors on cypress12.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/5075827470/jobs/9117419180?pr=676

https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/5075844173/jobs/9117451716?pr=668

2023-05-26 00:04 UTC, ananzh commented
Cypress functional test fixed PR: https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/682

2023-05-31 19:57 UTC, kavilla commented
Is this still slated for 2.8?

2023-06-01 02:38 UTC, peterzhuamazon commented
There are a lot more tests so we will postpone this.

2023-08-15 16:06 UTC, cwperks commented
Rebasing to `feature/cypress12`. This will be worked on in a feature branch to determine all tests that need to be updated to upgrade cypress from v9 to v12.

2023-08-24 16:48 UTC, cwperks commented
Could a maintainer of this repo please review this / merge this into the feature (`feature/cypress12`) branch?

I plan to open up issues in all of the dashboards plugin repos to ensure their tests run with Cypress12 and request that any dashboards plugin that needs to update tests make a PR against the `feature/cypress12` branch to show the tests working.

Once all dashboards plugins have verified their tests run with Cypress12 we can proceed to merging the feature branch into main.

2023-08-24 16:57 UTC, peterzhuamazon reviewed
This will need more changes from individual plugin repos.
And @cwperks @RyanL1997 will help with that meta issue.

Thanks

2023-08-24 17:05 UTC, merged